### ISSUE TITLE
Display previous run for announcer

### ISSUE THREAD

**Issue by vanteer** [event-cell/core#31]

**Comment by myberlina** [comment]
Issues  31, 30, 22, and less obviously 23, 24  could all possibly be addressed by:
Look at split 2 table for current car, rather than start beam (time):
   There is really nothing to report until the 1st sector is complete.
   The out of order issues that prompted  23 and 24  were putting in DNS (Did not start) entries in
      #23 : when car (n) does not rock up to the start line, if we start n+1, get confirmation that car n will not be participating in this run.  If I then DNS  car  n, the anouncer screen displays  n  instead of  n+1.  By looking at split 1 instead this problem is side-stepped.
      #24 :  In this case, at lunchtime (after run 3) when populating the start lists for run 4-6, I flagged a few cars that I knew had gone home as DNS.  This meant that the announcer screen thought that the current run was run 6, instead of run 4.  Not completely sure how current run is determined, but as removing those DNS entries solved the issue, I assume that the start time table is being used.  So again, moving to split 2 table should side step the issue.

   By not changing until the new car triggers split 2 (or up to 4 seconds after based on the polling interval) this gives the announcer time to finish reading the results.

    Another possible even better solution would be to make using Split 1 or Split 2 table configurable though the same page that selects the event.  This would allow us to use Split 2 on single lap events, and Split 1 on double lap events (in both cases when the car enters the circular part of the track)

Also assuming it is not a common code section.  Having the announcer trigger on split 2 makes sense, for the main display board, it should always trigger on  split 1.

**Comment by vanteer** [comment]
I might have already fixed this by looking at run # from online.scdb.  Need to confirm.

**Comment by vanteer** [comment]
Closing this for the moment as the timing only switches after interval 1
